# Project 05 — Experiment 2: Curated Dataset V3, Retraining, and Experiment Comparison

This notebook preserves the completed first experiment, builds a higher-quality
instruction dataset without using the held-out benchmark as training data,
trains a new FLAN-T5-base LoRA adapter, evaluates it on the same 80-prompt
benchmark, and compares Experiment 2 directly with Experiment 1.

**Release rule:** Experiment 1 is archived, not deleted. Experiment 2 is not
promoted until automated comparison and human factual review are complete.

## 0. Resolve the project root

In [1]:
from pathlib import Path
from datetime import datetime
import json
import os
import sys

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
PROJECT_ROOT = PROJECT_ROOT.resolve()
sys.path.insert(0, str(PROJECT_ROOT))

assert (PROJECT_ROOT / "src").exists(), "Open Jupyter from Project 05 or its notebooks folder."
print("Project root:", PROJECT_ROOT)

Project root: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm

## 1. Experiment controls and stable output paths

In [2]:
EXPERIMENT1_RUN_NAME = "flan_t5_base_lora_20260730_120312"
EXPERIMENT1_DIR = PROJECT_ROOT / "outputs" / "experiments" / EXPERIMENT1_RUN_NAME
assert EXPERIMENT1_DIR.exists(), f"Experiment 1 was not found: {EXPERIMENT1_DIR}"

ACTIVE_RUN_FILE = PROJECT_ROOT / "outputs" / "experiment2_active_run.json"
if ACTIVE_RUN_FILE.exists():
    active_run = json.loads(ACTIVE_RUN_FILE.read_text(encoding="utf-8"))
    EXPERIMENT2_RUN_NAME = active_run["run_name"]
else:
    EXPERIMENT2_RUN_NAME = f"flan_t5_base_lora_exp2_v3_{datetime.now():%Y%m%d_%H%M%S}"
    ACTIVE_RUN_FILE.parent.mkdir(parents=True, exist_ok=True)
    ACTIVE_RUN_FILE.write_text(
        json.dumps({"run_name": EXPERIMENT2_RUN_NAME}, indent=2),
        encoding="utf-8",
    )

EXPERIMENT2_DIR = PROJECT_ROOT / "outputs" / "experiments" / EXPERIMENT2_RUN_NAME
EXPERIMENT2_DIR.mkdir(parents=True, exist_ok=True)

CREATE_FULL_EXPERIMENT1_ZIP = True
REUSE_EXPERIMENT1_TEACHER_RECORDS = False
RUN_TRAINING = True
RUN_EVALUATION = True
PROMOTE_EXPERIMENT2 = False

print("Experiment 1:", EXPERIMENT1_DIR)
print("Experiment 2:", EXPERIMENT2_DIR)
print("Reuse Experiment 1 teacher records:", REUSE_EXPERIMENT1_TEACHER_RECORDS)

Experiment 1: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_20260730_120312
Experiment 2: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452
Reuse Experiment 1 teacher records: False

## 2. Preserve Experiment 1

This creates checksums, an experiment card, a summary, a notebook snapshot, and
an optional full ZIP. The original folder remains exactly where it is.

In [3]:
from src.experiment_archive import archive_experiment

archive_result = archive_experiment(
    EXPERIMENT1_DIR,
    PROJECT_ROOT / "outputs" / "experiment_archives",
    archive_label="experiment_1_initial_lora",
    create_full_zip=CREATE_FULL_EXPERIMENT1_ZIP,
    extra_files=[
        PROJECT_ROOT / "notebooks" / "05_full_training_evaluation_pipeline.ipynb"
    ],
)
display(archive_result)

assert EXPERIMENT1_DIR.exists(), "The original Experiment 1 folder must remain."
assert archive_result["source_still_exists"] is True

{'status': 'archived_without_deleting_source',
 'source_experiment': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiments\\flan_t5_base_lora_20260730_120312',
 'source_still_exists': True,
 'archive_directory': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiment_archives\\experiment_1_initial_lora',
 'full_zip': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiment_archives\\experiment_1_initial_lora\\experiment_1_initial_lora_full.zip',
 'summary_file': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiment_archives\\experiment_1_initial_lora\\experiment_1_summary.json',
 'card_file': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiment_archives\\experiment_1_initial_lora\\EXPERIMENT_1_CARD.md',
 'manifest_file': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiment_archives\\experiment_1_initial_lora\\experiment_manifest.json',
 'checksums_file': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiment_archives\\experiment_1_initial_lora\\sha256sums.txt',
 'file_count': 53}

## 3. Summarize the weaknesses found in Experiment 1

In [4]:
import pandas as pd

exp1_lora_review_path = (
    EXPERIMENT1_DIR / "evaluation" / "lora_model" / "manual_review_results.csv"
)
exp1_comparison_review_path = (
    EXPERIMENT1_DIR / "evaluation" / "comparison" / "per_example_base_vs_lora.csv"
)
assert exp1_lora_review_path.exists()
assert exp1_comparison_review_path.exists()

exp1_review = pd.read_csv(exp1_lora_review_path)
rating_columns = [
    "human_factuality_1_to_5",
    "human_relevance_1_to_5",
    "human_clarity_1_to_5",
    "human_instruction_following_1_to_5",
]

weakness_by_topic = (
    exp1_review
    .groupby(["topic", "category"], dropna=False)[rating_columns]
    .mean()
    .reset_index()
    .sort_values(
        ["human_factuality_1_to_5", "human_instruction_following_1_to_5"]
    )
)
display(weakness_by_topic.head(30))

weakness_output = EXPERIMENT2_DIR / "experiment1_weakness_summary.csv"
weakness_by_topic.to_csv(weakness_output, index=False)
print("Saved:", weakness_output)

,topic,category,human_factuality_1_to_5,human_relevance_1_to_5,human_clarity_1_to_5,human_instruction_following_1_to_5
1,BERTScore,Quality analytics,1.0,2.0,2.0,1.0
3,F1-score,Quality analytics,1.0,2.0,1.0,1.0
5,LoRA,Quality analytics,1.0,2.0,2.0,1.0
7,MAE,Quality analytics,1.0,2.0,2.0,1.0
9,PR-AUC,Quality analytics,1.0,2.0,2.0,1.0
10,R-squared,Metric explanation,1.0,2.0,2.0,1.0
13,RMSE,Quality analytics,1.0,2.0,2.0,1.0
15,ROC-AUC,Quality analytics,1.0,2.0,2.0,1.0
17,attention,Quality analytics,1.0,2.0,2.0,1.0
20,class imbalance,Concept explanation,1.0,2.0,2.0,1.0
21,class imbalance,Quality analytics,1.0,2.0,2.0,1.0
22,classification,Concept explanation,1.0,2.0,2.0,1.0
26,data leakage,Concept explanation,1.0,2.0,2.0,1.0
27,data leakage,Quality analytics,1.0,2.0,2.0,1.0
31,feature engineering,Quality analytics,1.0,2.0,2.0,1.0
34,hallucination,Concept explanation,1.0,2.0,2.0,1.0
35,hallucination,Quality analytics,1.0,2.0,2.0,1.0
36,instruction tuning,Concept explanation,1.0,2.0,2.0,1.0
37,instruction tuning,Quality analytics,1.0,2.0,2.0,1.0
38,k-means clustering,Concept explanation,1.0,1.0,2.0,1.0
39,k-means clustering,Quality analytics,1.0,2.0,2.0,1.0
40,k-nearest neighbors,Concept explanation,1.0,1.0,2.0,1.0
41,k-nearest neighbors,Quality analytics,1.0,2.0,2.0,1.0
44,missing values,Concept explanation,1.0,2.0,2.0,1.0
45,missing values,Quality analytics,1.0,2.0,2.0,1.0
50,outliers,Concept explanation,1.0,2.0,2.0,1.0
53,overfitting,Quality analytics,1.0,2.0,2.0,1.0
55,precision,Quality analytics,1.0,1.0,3.0,1.0
57,principal component analysis,Quality analytics,1.0,2.0,2.0,1.0
58,random forest,Concept explanation,1.0,2.0,2.0,1.0

Saved: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\experiment1_weakness_summary.csv

## 4. Build the Version 3 curated dataset

The default intentionally does **not** reuse the weak teacher-generated records
from Experiment 1. It combines the original self-authored seed set with
expert-curated topic cards, comparisons, code examples, and workflow answers.
The benchmark is used only for leakage screening.

In [5]:
from src.experiment2_dataset import build_dataset_v3

DATASET_V3_PATH = PROJECT_ROOT / "data" / "ml_ds_instruction_dataset_v3.jsonl"
DATASET_V3_REPORT_DIR = EXPERIMENT2_DIR / "dataset_build"

dataset_v3_result = build_dataset_v3(
    seed_dataset_path=PROJECT_ROOT / "data" / "ml_ds_instruction_dataset.jsonl",
    previous_v2_path=PROJECT_ROOT / "data" / "ml_ds_instruction_dataset_v2.jsonl",
    benchmark_path=PROJECT_ROOT / "data" / "benchmark_prompts_v2.jsonl",
    topic_cards_path=PROJECT_ROOT / "data" / "curated_topic_cards_v3.json",
    comparisons_path=PROJECT_ROOT / "data" / "curated_comparisons_v3.json",
    code_examples_path=PROJECT_ROOT / "data" / "curated_code_examples_v3.json",
    workflows_path=PROJECT_ROOT / "data" / "curated_workflows_v3.json",
    rules_path=PROJECT_ROOT / "data" / "experiment2_quality_rules.json",
    output_dataset_path=DATASET_V3_PATH,
    output_report_dir=DATASET_V3_REPORT_DIR,
    reuse_teacher_records=REUSE_EXPERIMENT1_TEACHER_RECORDS,
    seed=52,
)
display(dataset_v3_result)

assert dataset_v3_result["report"]["final_records"] >= 400
assert dataset_v3_result["report"]["validation_records"] > 0
assert dataset_v3_result["report"]["test_records"] > 0

{'status': 'completed',
 'dataset_path': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\data\\ml_ds_instruction_dataset_v3.jsonl',
 'reuse_teacher_records': False,
 'report': {'seed_records_loaded': 93,
  'previous_v2_records_loaded': 543,
  'previous_v2_records_reused': 0,
  'curated_topic_records': 275,
  'curated_comparison_records': 40,
  'curated_code_records': 20,
  'curated_workflow_records': 15,
  'rejected_quality': 0,
  'rejected_benchmark_overlap': 0,
  'rejected_near_duplicate': 0,
  'final_records': 442,
  'train_records': 352,
  'validation_records': 45,
  'test_records': 45,
  'output_word_mean': 49.03,
  'output_word_median': 48.0,
  'source_counts': {'expert-curated-v3-topic-card': 275,
   'expert-curated-v3-workflow': 14,
   'expert-curated-v3-comparison': 40,
   'expert-curated-v3-code': 20,
   'self-authored-synthetic': 93},
  'category_counts': {'Example generation': 61,
   'Data Science workflow': 12,
   'Algorithm comparison': 30,
   'Concept explanation': 90,
   'Small code example': 26,
   'Quality analytics': 61,
   'Beginner-friendly explanation': 61,
   'Interview-style answer': 81,
   'Metric explanation': 10,
   'ML project guidance': 10},
  'difficulty_counts': {'intermediate': 312, 'advanced': 47, 'beginner': 83}},
 'base_validation_report': {'total_records': 443,
  'valid_records': 442,
  'removed_records': 1,
  'empty_instructions': 0,
  'empty_outputs': 0,
  'duplicate_instructions': 0,
  'too_short_outputs': 0,
  'too_long_outputs': 0,
  'possible_pii': 0,
  'confidential_references': 1},
 'review_sample': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiments\\flan_t5_base_lora_exp2_v3_20260730_135452\\dataset_build\\dataset_v3_review_sample.csv',
 'rejection_log': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiments\\flan_t5_base_lora_exp2_v3_20260730_135452\\dataset_build\\dataset_v3_rejection_log.json',
 'important_note': 'benchmark_prompts_v2.jsonl was used only for leakage screening, never as training data.'}

## 5. Review the Version 3 dataset and approve it

In [6]:
dataset_v3_df = pd.read_json(DATASET_V3_PATH, lines=True)
print("Dataset shape:", dataset_v3_df.shape)

display(
    dataset_v3_df.groupby(["category", "difficulty"])
    .size()
    .rename("examples")
    .reset_index()
    .sort_values(["category", "difficulty"])
)

review_sample_path = DATASET_V3_REPORT_DIR / "dataset_v3_review_sample.csv"
review_sample = pd.read_csv(review_sample_path)
display(
    review_sample[
        ["instruction", "output", "category", "difficulty", "topic", "source", "split"]
    ]
)

print("Review sample file:", review_sample_path)
print("Open it in Excel if a wider view is easier.")

Dataset shape: (442, 9)

                         category    difficulty  examples
0            Algorithm comparison  intermediate        30
1   Beginner-friendly explanation      beginner        61
2             Concept explanation      advanced         2
3             Concept explanation      beginner        16
4             Concept explanation  intermediate        72
5           Data Science workflow      advanced         3
6           Data Science workflow  intermediate         9
7              Example generation      beginner         6
8              Example generation  intermediate        55
9          Interview-style answer      advanced        20
10         Interview-style answer  intermediate        61
11            ML project guidance      advanced         2
12            ML project guidance  intermediate         8
13             Metric explanation  intermediate        10
14              Quality analytics  intermediate        61
15             Small code example      advanced        20
16             Small code example  intermediate         6

,instruction,output,category,difficulty,topic,source,split
0,Compare random forest and gradient boosting.,Random forest builds many independent trees an...,Algorithm comparison,intermediate,ensemble learning,self-authored-synthetic,train
1,Contrast ROC-AUC with PR-AUC and give a decisi...,Core difference: ROC-AUC summarizes ranking ac...,Algorithm comparison,intermediate,ROC-AUC vs PR-AUC,expert-curated-v3-comparison,validation
2,Compare clustering and classification.,Clustering discovers groups without target lab...,Algorithm comparison,intermediate,learning paradigms,self-authored-synthetic,test
3,Contrast overfitting with underfitting and giv...,Core difference: Overfitting captures training...,Algorithm comparison,intermediate,overfitting vs underfitting,expert-curated-v3-comparison,train
4,Explain data drift to a beginner without using...,The model sees different feature values or pop...,Beginner-friendly explanation,beginner,data drift,expert-curated-v3-topic-card,train
5,Explain Transformer to a beginner without usin...,Each token can directly combine information fr...,Beginner-friendly explanation,beginner,Transformer,expert-curated-v3-topic-card,test
6,Explain full fine-tuning to a beginner without...,"The entire model can adapt, providing high cap...",Beginner-friendly explanation,beginner,full fine-tuning,expert-curated-v3-topic-card,train
7,Explain model deployment to a beginner without...,"Deployment connects model artifacts, preproces...",Beginner-friendly explanation,beginner,model deployment,expert-curated-v3-topic-card,train
8,Teach the core idea of L1 regularization using...,Definition: L1 regularization adds the absolut...,Concept explanation,intermediate,L1 regularization,expert-curated-v3-topic-card,validation
9,Teach the core idea of feature selection using...,Definition: Feature selection chooses a subset...,Concept explanation,intermediate,feature selection,expert-curated-v3-topic-card,validation
10,Teach the core idea of R-squared using a defin...,Definition: R-squared is the proportion of tar...,Concept explanation,intermediate,R-squared,expert-curated-v3-topic-card,train
11,Teach the core idea of decision tree using a d...,Definition: A decision tree recursively splits...,Concept explanation,intermediate,decision tree,expert-curated-v3-topic-card,train
12,Perform model error analysis.,Create a table of false positives and false ne...,Data Science workflow,intermediate,end-to-end workflow,self-authored-synthetic,train
13,Handle missing values.,"Measure missingness by column and segment, inv...",Data Science workflow,intermediate,end-to-end workflow,self-authored-synthetic,train
14,Describe how to design a held-out benchmark fo...,"Cover the supported topics, task types, diffic...",Data Science workflow,advanced,benchmark design,expert-curated-v3-workflow,train
15,Outline a leakage-safe workflow for building a...,"1. Define the prediction time, positive class,...",Data Science workflow,advanced,quality classification workflow,expert-curated-v3-workflow,train
16,Create a short learning example that demonstra...,Example: A large labeled corpus can be used to...,Example generation,intermediate,full fine-tuning,expert-curated-v3-topic-card,test
17,Create a short learning example that demonstra...,Example: Lasso regression can perform predicti...,Example generation,intermediate,L1 regularization,expert-curated-v3-topic-card,train
18,Create a short learning example that demonstra...,Example: A classifier can learn from inspectio...,Example generation,intermediate,supervised learning,expert-curated-v3-topic-card,train
19,Generate a small example of threshold tuning.,A fraud model outputs probabilities. At thresh...,Example generation,beginner,applied machine learning,self-authored-synthetic,train
20,Answer an interview question about long short-...,An LSTM is a recurrent architecture with gates...,Interview-style answer,intermediate,long short-term memory network,expert-curated-v3-topic-card,train
21,Answer an interview question about quality ana...,Quality analytics classification predicts a di...,Interview-style answer,intermediate,quality analytics classification,expert-curated-v3-topic-card,train
22,Answer an interview question about F1-score in...,F1-score is the harmonic mean of precision and...,Interview-style answer,intermediate,F1-score,expert-curated-v3-topic-card,train
23,Answer an interview question about underfittin...,Underfitting occurs when a model is too simple...,Interview-style answer,intermediate,underfitting,expert-curated-v3-topic-card,test
24,Create a checklist for deciding whether a LoRA...,Confirm that the adapter and tokenizer load ag...,ML project guidance,intermediate,deployment readiness,expert-curated-v3-workflow,train
25,Outline a human factual-review workflow for an...,Use a held-out prompt set with reference answe...,ML project guidance,intermediate,LLM factual review,expert-curated-v3-workflow,train
26,Explain why a second experiment should improve...,If the first adapter produces fluent but incor...,ML project guidance,intermediate,second experiment decision,expert-curated-v3-workflow,train
27,Build a binary classification project.,"Define the decision and positive class, collec...",ML project guidance,intermediate,end-to-end workflow,self-authored-synthetic,validation
28,Explain BERTScore and mention one limitation.,BERTScore compares candidate and reference tex...,Metric explanation,intermediate,model evaluation,self-authored-synthetic,train
29,Explain ROC-AUC and mention one limitation.,ROC-AUC measures how well a classifier ranks p...,Metric explanation,intermediate,model evaluation,self-authored-synthetic,train
30,Explain recall and mention one limitation.,Recall is true positives divided by all actual...,Metric explanation,intermediate,model evaluation,self-authored-synthetic,train
31,Explain MAE and mention one limitation.,Mean absolute error averages the absolute pred...,Metric explanation,intermediate,model evaluation,self-authored-synthetic,test
32,Describe a safe ML approach for root-cause pri...,"Use historical, non-confidential features to r...",Quality analytics,intermediate,quality analytics,self-authored-synthetic,train
33,"Give a concrete, non-confidential quality anal...",Quality use case: Report F1 together with the ...,Quality analytics,intermediate,F1-score,expert-curated-v3-topic-card,train
34,"Give a concrete, non-confidential quality anal...",Quality use case: Use PR-AUC to compare rare-f...,Quality analytics,intermediate,PR-AUC,expert-curated-v3-topic-card,validation
35,"Give a concrete, non-confidential quality anal...",Quality use case: Track missing-rate trends by...,Quality analytics,intermediate,missing values,expert-curated-v3-topic-card,train
36,Show how to inspect precision and recall at mu...,```python import numpy as np from sklearn.metr...,Small code example,advanced,threshold tuning,expert-curated-v3-code,train
37,Write a deterministic generation example for a...,"```python prompt = ( ""Instruction: "" ""Explain ...",Small code example,advanced,inference generation,expert-curated-v3-code,train
38,Show a PEFT LoRA configuration for a T5 sequen...,"```python from peft import LoraConfig, TaskTyp...",Small code example,advanced,LoRA configuration,expert-curated-v3-code,train
39,Give a logistic-regression example that handle...,```python from sklearn.linear_model import Log...,Small code example,advanced,class weights,expert-curated-v3-code,validation
40,Give a portfolio-ready interview answer compar...,Calibration asks whether probabilities match o...,Interview-style answer,advanced,probability calibration vs discrimination,expert-curated-v3-comparison,train
41,Write a short example that evaluates probabili...,```python from sklearn.calibration import cali...,Small code example,advanced,calibration curve,expert-curated-v3-code,test
42,Give a portfolio-ready interview answer compar...,One-hot encoding gives each category an indepe...,Interview-style answer,advanced,one-hot encoding vs embeddings,expert-curated-v3-comparison,train
43,Give a portfolio-ready interview answer compar...,Precision measures correctness among predicted...,Interview-style answer,advanced,precision vs recall,expert-curated-v3-comparison,train
44,Give a portfolio-ready interview answer compar...,ROC-AUC summarizes ranking across true-positiv...,Interview-style answer,advanced,ROC-AUC vs PR-AUC,expert-curated-v3-comparison,train
45,Give a portfolio-ready interview answer compar...,Batch inference scores many records on a sched...,Interview-style answer,advanced,batch inference vs online inference,expert-curated-v3-comparison,validation
46,Show how to evaluate a preprocessing and logis...,```python from sklearn.model_selection import ...,Small code example,advanced,cross validation pipeline,expert-curated-v3-code,train
47,Show how to calculate permutation importance o...,```python from sklearn.inspection import permu...,Small code example,advanced,permutation importance,expert-curated-v3-code,train
48,Give a portfolio-ready interview answer compar...,"A fixed split uses one validation partition, w...",Interview-style answer,advanced,train validation test split vs cross-validation,expert-curated-v3-comparison,train
49,Create a concise evaluation snippet for precis...,```python from sklearn.metrics import ( classi...,Small code example,advanced,classification metrics,expert-curated-v3-code,test
50,Give a portfolio-ready interview answer compar...,L1 encourages sparse coefficients and can set ...,Interview-style answer,advanced,L1 regularization vs L2 regularization,expert-curated-v3-comparison,train
51,Give a portfolio-ready interview answer compar...,An LSTM is a gated recurrent network designed ...,Interview-style answer,advanced,recurrent neural network vs long short-term me...,expert-curated-v3-comparison,train
52,Explain how to compare two LoRA experiments fa...,"Use the same base model, tokenizer, prompt tem...",ML project guidance,advanced,experiment comparison,expert-curated-v3-workflow,train
53,Give a portfolio-ready interview answer compar...,A generative model represents how data or outp...,Interview-style answer,advanced,generative model vs discriminative model,expert-curated-v3-comparison,test
54,Create a simple residual-analysis table for a ...,```python prediction = model.predict(X_test) r...,Small code example,advanced,residual analysis,expert-curated-v3-code,train
55,Give a portfolio-ready interview answer compar...,"Overfitting captures training-specific noise, ...",Interview-style answer,advanced,overfitting vs underfitting,expert-curated-v3-comparison,train
56,Give a portfolio-ready interview answer compar...,"Classification predicts categories, whereas re...",Interview-style answer,advanced,classification vs regression,expert-curated-v3-comparison,validation
57,Explain how to choose between a simple baselin...,Begin with a transparent baseline that establi...,ML project guidance,advanced,model selection,expert-curated-v3-workflow,train
58,Explain calibration in simple terms.,A calibrated classifier produces probabilities...,Concept explanation,advanced,model evaluation,self-authored-synthetic,train
59,Show how to save a compact experiment metadata...,```python import json from pathlib import Path...,Small code example,advanced,experiment metadata,expert-curated-v3-code,train

Review sample file: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\dataset_build\dataset_v3_review_sample.csv
Open it in Excel if a wider view is easier.

In [7]:
import os

dataset_review_dir = EXPERIMENT2_DIR / "dataset_build"

print("Dataset review directory:")
print(dataset_review_dir)

print("\nReview sample:")
print(dataset_review_dir / "dataset_v3_review_sample.csv")

print("\nQuality report:")
print(dataset_review_dir / "dataset_v3_quality_report.json")

print("\nRejection log:")
print(dataset_review_dir / "dataset_v3_rejection_log.json")

os.startfile(str(dataset_review_dir))

Dataset review directory:
C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\dataset_build

Review sample:
C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\dataset_build\dataset_v3_review_sample.csv

Quality report:
C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\dataset_build\dataset_v3_quality_report.json

Rejection log:
C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\dataset_build\dataset_v3_rejection_log.json

In [8]:
import json
import pandas as pd

review_path = dataset_review_dir / "dataset_v3_review_sample.csv"
quality_report_path = dataset_review_dir / "dataset_v3_quality_report.json"
rejection_log_path = dataset_review_dir / "dataset_v3_rejection_log.json"

review_df = pd.read_csv(review_path)

print("=" * 70)
print("DATASET V3 REVIEW SAMPLE")
print("=" * 70)
print(f"Review records: {len(review_df)}")
print(f"Columns: {review_df.columns.tolist()}")

display(review_df)

======================================================================
DATASET V3 REVIEW SAMPLE
======================================================================
Review records: 60
Columns: ['id', 'instruction', 'input', 'output', 'category', 'difficulty', 'topic', 'source', 'split']

,id,instruction,input,output,category,difficulty,topic,source,split
0,ml_ds_v3_0109,Compare random forest and gradient boosting.,NaN,Random forest builds many independent trees an...,Algorithm comparison,intermediate,ensemble learning,self-authored-synthetic,train
1,ml_ds_v3_0228,Contrast ROC-AUC with PR-AUC and give a decisi...,"Use the headings Core difference, Prefer the f...",Core difference: ROC-AUC summarizes ranking ac...,Algorithm comparison,intermediate,ROC-AUC vs PR-AUC,expert-curated-v3-comparison,validation
2,ml_ds_v3_0257,Compare clustering and classification.,NaN,Clustering discovers groups without target lab...,Algorithm comparison,intermediate,learning paradigms,self-authored-synthetic,test
3,ml_ds_v3_0223,Contrast overfitting with underfitting and giv...,"Use the headings Core difference, Prefer the f...",Core difference: Overfitting captures training...,Algorithm comparison,intermediate,overfitting vs underfitting,expert-curated-v3-comparison,train
4,ml_ds_v3_0312,Explain data drift to a beginner without using...,Include a practical example and one limitation...,The model sees different feature values or pop...,Beginner-friendly explanation,beginner,data drift,expert-curated-v3-topic-card,train
5,ml_ds_v3_0139,Explain Transformer to a beginner without usin...,Include a practical example and one limitation...,Each token can directly combine information fr...,Beginner-friendly explanation,beginner,Transformer,expert-curated-v3-topic-card,test
6,ml_ds_v3_0235,Explain full fine-tuning to a beginner without...,Include a practical example and one limitation...,"The entire model can adapt, providing high cap...",Beginner-friendly explanation,beginner,full fine-tuning,expert-curated-v3-topic-card,train
7,ml_ds_v3_0441,Explain model deployment to a beginner without...,Include a practical example and one limitation...,"Deployment connects model artifacts, preproces...",Beginner-friendly explanation,beginner,model deployment,expert-curated-v3-topic-card,train
8,ml_ds_v3_0368,Teach the core idea of L1 regularization using...,Write for an intermediate ML learner and keep ...,Definition: L1 regularization adds the absolut...,Concept explanation,intermediate,L1 regularization,expert-curated-v3-topic-card,validation
9,ml_ds_v3_0131,Teach the core idea of feature selection using...,Write for an intermediate ML learner and keep ...,Definition: Feature selection chooses a subset...,Concept explanation,intermediate,feature selection,expert-curated-v3-topic-card,validation
10,ml_ds_v3_0027,Teach the core idea of R-squared using a defin...,Write for an intermediate ML learner and keep ...,Definition: R-squared is the proportion of tar...,Concept explanation,intermediate,R-squared,expert-curated-v3-topic-card,train
11,ml_ds_v3_0197,Teach the core idea of decision tree using a d...,Write for an intermediate ML learner and keep ...,Definition: A decision tree recursively splits...,Concept explanation,intermediate,decision tree,expert-curated-v3-topic-card,train
12,ml_ds_v3_0161,Perform model error analysis.,NaN,Create a table of false positives and false ne...,Data Science workflow,intermediate,end-to-end workflow,self-authored-synthetic,train
13,ml_ds_v3_0058,Handle missing values.,NaN,"Measure missingness by column and segment, inv...",Data Science workflow,intermediate,end-to-end workflow,self-authored-synthetic,train
14,ml_ds_v3_0230,Describe how to design a held-out benchmark fo...,Present actionable steps and include evaluatio...,"Cover the supported topics, task types, diffic...",Data Science workflow,advanced,benchmark design,expert-curated-v3-workflow,train
15,ml_ds_v3_0004,Outline a leakage-safe workflow for building a...,Present actionable steps and include evaluatio...,"1. Define the prediction time, positive class,...",Data Science workflow,advanced,quality classification workflow,expert-curated-v3-workflow,train
16,ml_ds_v3_0009,Create a short learning example that demonstra...,The answer must separate the example from the ...,Example: A large labeled corpus can be used to...,Example generation,intermediate,full fine-tuning,expert-curated-v3-topic-card,test
17,ml_ds_v3_0116,Create a short learning example that demonstra...,The answer must separate the example from the ...,Example: Lasso regression can perform predicti...,Example generation,intermediate,L1 regularization,expert-curated-v3-topic-card,train
18,ml_ds_v3_0181,Create a short learning example that demonstra...,The answer must separate the example from the ...,Example: A classifier can learn from inspectio...,Example generation,intermediate,supervised learning,expert-curated-v3-topic-card,train
19,ml_ds_v3_0307,Generate a small example of threshold tuning.,NaN,A fraud model outputs probabilities. At thresh...,Example generation,beginner,applied machine learning,self-authored-synthetic,train
20,ml_ds_v3_0168,Answer an interview question about long short-...,"State what it is, when it is useful, and one c...",An LSTM is a recurrent architecture with gates...,Interview-style answer,intermediate,long short-term memory network,expert-curated-v3-topic-card,train
21,ml_ds_v3_0256,Answer an interview question about quality ana...,"State what it is, when it is useful, and one c...",Quality analytics classification predicts a di...,Interview-style answer,intermediate,quality analytics classification,expert-curated-v3-topic-card,train
22,ml_ds_v3_0288,Answer an interview question about F1-score in...,"State what it is, when it is useful, and one c...",F1-score is the harmonic mean of precision and...,Interview-style answer,intermediate,F1-score,expert-curated-v3-topic-card,train
23,ml_ds_v3_0261,Answer an interview question about underfittin...,"State what it is, when it is useful, and one c...",Underfitting occurs when a model is too simple...,Interview-style answer,intermediate,underfitting,expert-curated-v3-topic-card,test
24,ml_ds_v3_0079,Create a checklist for deciding whether a LoRA...,Present actionable steps and include evaluatio...,Confirm that the adapter and tokenizer load ag...,ML project guidance,intermediate,deployment readiness,expert-curated-v3-workflow,train
25,ml_ds_v3_0128,Outline a human factual-review workflow for an...,Present actionable steps and include evaluatio...,Use a held-out prompt set with reference answe...,ML project guidance,intermediate,LLM factual review,expert-curated-v3-workflow,train
26,ml_ds_v3_0104,Explain why a second experiment should improve...,Present actionable steps and include evaluatio...,If the first adapter produces fluent but incor...,ML project guidance,intermediate,second experiment decision,expert-curated-v3-workflow,train
27,ml_ds_v3_0243,Build a binary classification project.,NaN,"Define the decision and positive class, collec...",ML project guidance,intermediate,end-to-end workflow,self-authored-synthetic,validation
28,ml_ds_v3_0138,Explain BERTScore and mention one limitation.,NaN,BERTScore compares candidate and reference tex...,Metric explanation,intermediate,model evaluation,self-authored-synthetic,train
29,ml_ds_v3_0204,Explain ROC-AUC and mention one limitation.,NaN,ROC-AUC measures how well a classifier ranks p...,Metric explanation,intermediate,model evaluation,self-authored-synthetic,train
30,ml_ds_v3_0073,Explain recall and mention one limitation.,NaN,Recall is true positives divided by all actual...,Metric explanation,intermediate,model evaluation,self-authored-synthetic,train
31,ml_ds_v3_0198,Explain MAE and mention one limitation.,NaN,Mean absolute error averages the absolute pred...,Metric explanation,intermediate,model evaluation,self-authored-synthetic,test
32,ml_ds_v3_0271,Describe a safe ML approach for root-cause pri...,NaN,"Use historical, non-confidential features to r...",Quality analytics,intermediate,quality analytics,self-authored-synthetic,train
33,ml_ds_v3_0263,"Give a concrete, non-confidential quality anal...","Use a manufacturing, inspection, complaint, or...",Quality use case: Report F1 together with the ...,Quality analytics,intermediate,F1-score,expert-curated-v3-topic-card,train
34,ml_ds_v3_0252,"Give a concrete, non-confidential quality anal...","Use a manufacturing, inspection, complaint, or...",Quality use case: Use PR-AUC to compare rare-f...,Quality analytics,intermediate,PR-AUC,expert-curated-v3-topic-card,validation
35,ml_ds_v3_0183,"Give a concrete, non-confidential quality anal...","Use a manufacturing, inspection, complaint, or...",Quality use case: Track missing-rate trends by...,Quality analytics,intermediate,missing values,expert-curated-v3-topic-card,train
36,ml_ds_v3_0071,Show how to inspect precision and recall at mu...,"Use Python and explain the leakage, evaluation...",```python import numpy as np from sklearn.metr...,Small code example,advanced,threshold tuning,expert-curated-v3-code,train
37,ml_ds_v3_0016,Write a deterministic generation example for a...,"Use Python and explain the leakage, evaluation...","```python prompt = ( ""Instruction: "" ""Explain ...",Small code example,advanced,inference generation,expert-curated-v3-code,train
38,ml_ds_v3_0068,Show a PEFT LoRA configuration for a T5 sequen...,"Use Python and explain the leakage, evaluation...","```python from peft import LoraConfig, TaskTyp...",Small code example,advanced,LoRA configuration,expert-curated-v3-code,train
39,ml_ds_v3_0126,Give a logistic-regression example that handle...,"Use Python and explain the leakage, evaluation...",```python from sklearn.linear_model import Log...,Small code example,advanced,class weights,expert-curated-v3-code,validation
40,ml_ds_v3_0376,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,Calibration asks whether probabilities match o...,Interview-style answer,advanced,probability calibration vs discrimination,expert-curated-v3-comparison,train
41,ml_ds_v3_0340,Write a short example that evaluates probabili...,"Use Python and explain the leakage, evaluation...",```python from sklearn.calibration import cali...,Small code example,advanced,calibration curve,expert-curated-v3-code,test
42,ml_ds_v3_0226,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,One-hot encoding gives each category an indepe...,Interview-style answer,advanced,one-hot encoding vs embeddings,expert-curated-v3-comparison,train
43,ml_ds_v3_0047,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,Precision measures correctness among predicted...,Interview-style answer,advanced,precision vs recall,expert-curated-v3-comparison,train
44,ml_ds_v3_0369,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,ROC-AUC summarizes ranking across true-positiv...,Interview-style answer,advanced,ROC-AUC vs PR-AUC,expert-curated-v3-comparison,train
45,ml_ds_v3_0103,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,Batch inference scores many records on a sched...,Interview-style answer,advanced,batch inference vs online inference,expert-curated-v3-comparison,validation
46,ml_ds_v3_0007,Show how to evaluate a preprocessing and logis...,"Use Python and explain the leakage, evaluation...",```python from sklearn.model_selection import ...,Small code example,advanced,cross validation pipeline,expert-curated-v3-code,train
47,ml_ds_v3_0320,Show how to calculate permutation importance o...,"Use Python and explain the leakage, evaluation...",```python from sklearn.inspection import permu...,Small code example,advanced,permutation importance,expert-curated-v3-code,train
48,ml_ds_v3_0020,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,"A fixed split uses one validation partition, w...",Interview-style answer,advanced,train validation test split vs cross-validation,expert-curated-v3-comparison,train
49,ml_ds_v3_0241,Create a concise evaluation snippet for precis...,"Use Python and explain the leakage, evaluation...",```python from sklearn.metrics import ( classi...,Small code example,advanced,classification metrics,expert-curated-v3-code,test
50,ml_ds_v3_0294,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,L1 encourages sparse coefficients and can set ...,Interview-style answer,advanced,L1 regularization vs L2 regularization,expert-curated-v3-comparison,train
51,ml_ds_v3_0393,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,An LSTM is a gated recurrent network designed ...,Interview-style answer,advanced,recurrent neural network vs long short-term me...,expert-curated-v3-comparison,train
52,ml_ds_v3_0373,Explain how to compare two LoRA experiments fa...,Present actionable steps and include evaluatio...,"Use the same base model, tokenizer, prompt tem...",ML project guidance,advanced,experiment comparison,expert-curated-v3-workflow,train
53,ml_ds_v3_0258,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,A generative model represents how data or outp...,Interview-style answer,advanced,generative model vs discriminative model,expert-curated-v3-comparison,test
54,ml_ds_v3_0219,Create a simple residual-analysis table for a ...,"Use Python and explain the leakage, evaluation...",```python prediction = model.predict(X_test) r...,Small code example,advanced,residual analysis,expert-curated-v3-code,train
55,ml_ds_v3_0030,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,"Overfitting captures training-specific noise, ...",Interview-style answer,advanced,overfitting vs underfitting,expert-curated-v3-comparison,train
56,ml_ds_v3_0364,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,"Classification predicts categories, whereas re...",Interview-style answer,advanced,classification vs regression,expert-curated-v3-comparison,validation
57,ml_ds_v3_0317,Explain how to choose between a simple baselin...,Present actionable steps and include evaluatio...,Begin with a transparent baseline that establi...,ML project guidance,advanced,model selection,expert-curated-v3-workflow,train
58,ml_ds_v3_0039,Explain calibration in simple terms.,NaN,A calibrated classifier produces probabilities...,Concept explanation,advanced,model evaluation,self-authored-synthetic,train
59,ml_ds_v3_0075,Show how to save a compact experiment metadata...,"Use Python and explain the leakage, evaluation...",```python import json from pathlib import Path...,Small code example,advanced,experiment metadata,expert-curated-v3-code,train

In [9]:
print("Examples by category:")

display(
    review_df["category"]
    .value_counts()
    .rename_axis("category")
    .reset_index(name="examples")
)

print("\nExamples by difficulty:")

display(
    review_df["difficulty"]
    .value_counts()
    .rename_axis("difficulty")
    .reset_index(name="examples")
)

Examples by category:

                        category  examples
0         Interview-style answer        15
1             Small code example        10
2            ML project guidance         6
3            Concept explanation         5
4           Algorithm comparison         4
5  Beginner-friendly explanation         4
6          Data Science workflow         4
7             Example generation         4
8             Metric explanation         4
9              Quality analytics         4

Examples by difficulty:

     difficulty  examples
0  intermediate        29
1      advanced        26
2      beginner         5

In [10]:
important_pattern = (
    "classification|regression|data leakage|cross-validation|"
    "standardization|precision|recall|f1|transformer|attention|"
    "lora|peft|quality analytics|code"
)

important_examples = review_df[
    review_df["topic"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.contains(important_pattern, regex=True)
]

display(
    important_examples.reset_index(drop=True)
)

,id,instruction,input,output,category,difficulty,topic,source,split
0,ml_ds_v3_0139,Explain Transformer to a beginner without usin...,Include a practical example and one limitation...,Each token can directly combine information fr...,Beginner-friendly explanation,beginner,Transformer,expert-curated-v3-topic-card,test
1,ml_ds_v3_0004,Outline a leakage-safe workflow for building a...,Present actionable steps and include evaluatio...,"1. Define the prediction time, positive class,...",Data Science workflow,advanced,quality classification workflow,expert-curated-v3-workflow,train
2,ml_ds_v3_0256,Answer an interview question about quality ana...,"State what it is, when it is useful, and one c...",Quality analytics classification predicts a di...,Interview-style answer,intermediate,quality analytics classification,expert-curated-v3-topic-card,train
3,ml_ds_v3_0288,Answer an interview question about F1-score in...,"State what it is, when it is useful, and one c...",F1-score is the harmonic mean of precision and...,Interview-style answer,intermediate,F1-score,expert-curated-v3-topic-card,train
4,ml_ds_v3_0271,Describe a safe ML approach for root-cause pri...,NaN,"Use historical, non-confidential features to r...",Quality analytics,intermediate,quality analytics,self-authored-synthetic,train
5,ml_ds_v3_0263,"Give a concrete, non-confidential quality anal...","Use a manufacturing, inspection, complaint, or...",Quality use case: Report F1 together with the ...,Quality analytics,intermediate,F1-score,expert-curated-v3-topic-card,train
6,ml_ds_v3_0068,Show a PEFT LoRA configuration for a T5 sequen...,"Use Python and explain the leakage, evaluation...","```python from peft import LoraConfig, TaskTyp...",Small code example,advanced,LoRA configuration,expert-curated-v3-code,train
7,ml_ds_v3_0047,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,Precision measures correctness among predicted...,Interview-style answer,advanced,precision vs recall,expert-curated-v3-comparison,train
8,ml_ds_v3_0020,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,"A fixed split uses one validation partition, w...",Interview-style answer,advanced,train validation test split vs cross-validation,expert-curated-v3-comparison,train
9,ml_ds_v3_0241,Create a concise evaluation snippet for precis...,"Use Python and explain the leakage, evaluation...",```python from sklearn.metrics import ( classi...,Small code example,advanced,classification metrics,expert-curated-v3-code,test
10,ml_ds_v3_0364,Give a portfolio-ready interview answer compar...,Do not claim that one is universally better.,"Classification predicts categories, whereas re...",Interview-style answer,advanced,classification vs regression,expert-curated-v3-comparison,validation

In [11]:
with open(quality_report_path, "r", encoding="utf-8") as file:
    quality_report = json.load(file)

display(quality_report)

{'status': 'completed',
 'dataset_path': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\data\\ml_ds_instruction_dataset_v3.jsonl',
 'reuse_teacher_records': False,
 'report': {'seed_records_loaded': 93,
  'previous_v2_records_loaded': 543,
  'previous_v2_records_reused': 0,
  'curated_topic_records': 275,
  'curated_comparison_records': 40,
  'curated_code_records': 20,
  'curated_workflow_records': 15,
  'rejected_quality': 0,
  'rejected_benchmark_overlap': 0,
  'rejected_near_duplicate': 0,
  'final_records': 442,
  'train_records': 352,
  'validation_records': 45,
  'test_records': 45,
  'output_word_mean': 49.03,
  'output_word_median': 48.0,
  'source_counts': {'expert-curated-v3-topic-card': 275,
   'expert-curated-v3-workflow': 14,
   'expert-curated-v3-comparison': 40,
   'expert-curated-v3-code': 20,
   'self-authored-synthetic': 93},
  'category_counts': {'Example generation': 61,
   'Data Science workflow': 12,
   'Algorithm comparison': 30,
   'Concept explanation': 90,
   'Small code example': 26,
   'Quality analytics': 61,
   'Beginner-friendly explanation': 61,
   'Interview-style answer': 81,
   'Metric explanation': 10,
   'ML project guidance': 10},
  'difficulty_counts': {'intermediate': 312, 'advanced': 47, 'beginner': 83}},
 'base_validation_report': {'total_records': 443,
  'valid_records': 442,
  'removed_records': 1,
  'empty_instructions': 0,
  'empty_outputs': 0,
  'duplicate_instructions': 0,
  'too_short_outputs': 0,
  'too_long_outputs': 0,
  'possible_pii': 0,
  'confidential_references': 1},
 'review_sample': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiments\\flan_t5_base_lora_exp2_v3_20260730_135452\\dataset_build\\dataset_v3_review_sample.csv',
 'rejection_log': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiments\\flan_t5_base_lora_exp2_v3_20260730_135452\\dataset_build\\dataset_v3_rejection_log.json',
 'important_note': 'benchmark_prompts_v2.jsonl was used only for leakage screening, never as training data.'}

In [12]:
with open(rejection_log_path, "r", encoding="utf-8") as file:
    rejection_log = json.load(file)

print("Rejected records:", len(rejection_log))

if rejection_log:
    display(pd.DataFrame(rejection_log).head(50))
else:
    print("No rejected records were recorded.")

Rejected records: 0
No rejected records were recorded.

In [13]:
DATASET_V3_HUMAN_REVIEW_APPROVED = True

if RUN_TRAINING and not DATASET_V3_HUMAN_REVIEW_APPROVED:
    raise RuntimeError(
        "Experiment 2 training is blocked. Review dataset_v3_review_sample.csv, "
        "correct any weak records, then set DATASET_V3_HUMAN_REVIEW_APPROVED = True."
    )

print("Dataset V3 human-review approval passed.")

Dataset V3 human-review approval passed.

## 6. Verify the RTX environment and Experiment 2 training configuration

In [14]:
import torch
from dataclasses import asdict
from src.config import ModelConfig
from src.experiment2_training import Experiment2TrainingConfig
from src.hardware_utils import detect_hardware

hardware = detect_hardware()
assert hardware.cuda_available, "CUDA is required."
assert "RTX 5090" in hardware.gpu_name, f"Unexpected GPU: {hardware.gpu_name}"

model_config = ModelConfig(
    base_model_id="google/flan-t5-base",
    max_input_length=512,
    max_target_length=256,
)
training_config = Experiment2TrainingConfig(
    r=32,
    lora_alpha=64,
    learning_rate=5e-5,
    num_train_epochs=5.0,
    warmup_steps=20,
    early_stopping_patience=2,
    seed=52,
)

display({
    "hardware": hardware.to_dict(),
    "model_config": asdict(model_config),
    "experiment2_training_config": asdict(training_config),
})

{'hardware': {'python_version': '3.12.10',
  'platform': 'Windows-11-10.0.26200-SP0',
  'torch_version': '2.12.1+cu132',
  'cuda_available': True,
  'cuda_version': '13.2',
  'cudnn_version': '92000',
  'gpu_name': 'NVIDIA GeForce RTX 5090',
  'gpu_vram_gb': 31.84,
  'compute_capability': '12.0',
  'bf16_supported': True,
  'recommended_precision': 'bf16',
  'recommended_model_id': 'google/flan-t5-base',
  'train_batch_size': 8,
  'eval_batch_size': 8,
  'gradient_accumulation_steps': 2,
  'gradient_checkpointing': False,
  'dataloader_num_workers': 4},
 'model_config': {'base_model_id': 'google/flan-t5-base',
  'adapter_id': '',
  'local_adapter_path': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\models\\lora_adapter',
  'max_input_length': 512,
  'max_target_length': 256,
  'device': 'auto',
  'torch_dtype': 'auto',
  'trust_remote_code': False},
 'experiment2_training_config': {'r': 32,
  'lora_alpha': 64,
  'lora_dropout': 0.05,
  'target_modules': ('q', 'v'),
  'learning_rate': 5e-05,
  'num_train_epochs': 5.0,
  'per_device_train_batch_size': 8,
  'per_device_eval_batch_size': 8,
  'gradient_accumulation_steps': 2,
  'warmup_steps': 20,
  'weight_decay': 0.01,
  'logging_steps': 10,
  'save_total_limit': 2,
  'seed': 52,
  'lr_scheduler_type': 'cosine',
  'label_smoothing_factor': 0.0,
  'max_grad_norm': 1.0,
  'early_stopping_patience': 2,
  'gradient_checkpointing': False,
  'dataloader_num_workers': 4,
  'group_by_length': True,
  'optim': 'adamw_torch'}}

## 7. Train the Experiment 2 FLAN-T5-base LoRA adapter

In [15]:
import gc
import shutil
import torch

partial_training_dir = EXPERIMENT2_DIR / "training"

print("Incomplete training directory:")
print(partial_training_dir)

if partial_training_dir.exists():
    shutil.rmtree(partial_training_dir)
    print("Incomplete Experiment 2 training directory deleted.")
else:
    print("No incomplete training directory was found.")

gc.collect()

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    print("RTX GPU cache cleared.")

Incomplete training directory:
C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\training
Incomplete Experiment 2 training directory deleted.
RTX GPU cache cleared.

In [16]:
from src.experiment2_training import train_experiment2_adapter

TRAINING_DIR = EXPERIMENT2_DIR / "training"

if RUN_TRAINING:
    experiment2_training_metadata = train_experiment2_adapter(
        DATASET_V3_PATH,
        TRAINING_DIR,
        model_config=model_config,
        training_config=training_config,
        hardware_profile=hardware,
    )
else:
    experiment2_training_metadata = json.loads(
        (TRAINING_DIR / "model_metadata.json").read_text(encoding="utf-8")
    )

display(experiment2_training_metadata)

EXPERIMENT2_ADAPTER_PATH = TRAINING_DIR / "lora_adapter"
assert (EXPERIMENT2_ADAPTER_PATH / "adapter_config.json").exists()
assert (EXPERIMENT2_ADAPTER_PATH / "adapter_model.safetensors").exists()
print("Experiment 2 adapter:", EXPERIMENT2_ADAPTER_PATH)

C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 282/282 [00:00<00:00, 2309.19it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

========================================================================
FLAN-T5 PRETRAINED CHECKPOINT VERIFICATION
========================================================================
Shared embedding loaded       : True
Encoder uses shared embedding : True
Decoder uses shared embedding : True
LM head uses shared embedding : False
Config tie_word_embeddings   : True
Pretrained FLAN-T5 embedding verification passed.

Tokenizing Experiment 2 train split: 100%|██████████| 352/352 [00:00<00:00, 7472.81 examples/s]
Tokenizing Experiment 2 validation split: 100%|██████████| 45/45 [00:00<00:00, 3168.12 examples/s]
Tokenizing Experiment 2 test split: 100%|██████████| 45/45 [00:00<00:00, 2645.28 examples/s]

trainable params: 3,538,944 || all params: 251,116,800 || trainable%: 1.4093

{'status': 'completed',
 'experiment': 'experiment_2_dataset_quality_upgrade',
 'base_model': 'google/flan-t5-base',
 'fine_tuning_method': 'LoRA/PEFT',
 'adapter_path': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiments\\flan_t5_base_lora_exp2_v3_20260730_135452\\training\\lora_adapter',
 'tokenizer_path': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiments\\flan_t5_base_lora_exp2_v3_20260730_135452\\training\\tokenizer',
 'dataset_path': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\data\\ml_ds_instruction_dataset_v3.jsonl',
 'dataset_validation': {'total_records': 442,
  'valid_records': 442,
  'removed_records': 0,
  'empty_instructions': 0,
  'empty_outputs': 0,
  'duplicate_instructions': 0,
  'too_short_outputs': 0,
  'too_long_outputs': 0,
  'possible_pii': 0,
  'confidential_references': 0},
 'dataset_split_sizes': {'train': 352, 'validation': 45, 'test': 45},
 'model_config': {'base_model_id': 'google/flan-t5-base',
  'adapter_id': '',
  'local_adapter_path': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\models\\lora_adapter',
  'max_input_length': 512,
  'max_target_length': 256,
  'device': 'auto',
  'torch_dtype': 'auto',
  'trust_remote_code': False},
 'training_config': {'r': 32,
  'lora_alpha': 64,
  'lora_dropout': 0.05,
  'target_modules': ('q', 'v'),
  'learning_rate': 5e-05,
  'num_train_epochs': 5.0,
  'per_device_train_batch_size': 8,
  'per_device_eval_batch_size': 8,
  'gradient_accumulation_steps': 2,
  'warmup_steps': 20,
  'weight_decay': 0.01,
  'logging_steps': 10,
  'save_total_limit': 2,
  'seed': 52,
  'lr_scheduler_type': 'cosine',
  'label_smoothing_factor': 0.0,
  'max_grad_norm': 1.0,
  'early_stopping_patience': 2,
  'gradient_checkpointing': False,
  'dataloader_num_workers': 4,
  'group_by_length': True,
  'optim': 'adamw_torch'},
 'hardware': {'python_version': '3.12.10',
  'platform': 'Windows-11-10.0.26200-SP0',
  'torch_version': '2.12.1+cu132',
  'cuda_available': True,
  'cuda_version': '13.2',
  'cudnn_version': '92000',
  'gpu_name': 'NVIDIA GeForce RTX 5090',
  'gpu_vram_gb': 31.84,
  'compute_capability': '12.0',
  'bf16_supported': True,
  'recommended_precision': 'bf16',
  'recommended_model_id': 'google/flan-t5-base',
  'train_batch_size': 8,
  'eval_batch_size': 8,
  'gradient_accumulation_steps': 2,
  'gradient_checkpointing': False,
  'dataloader_num_workers': 4},
 'package_versions': {'torch': '2.12.1+cu132', 'transformers': '5.14.1'},
 'model_loading_verification': {'shared_weight_loaded': True,
  'encoder_uses_shared_weight': True,
  'decoder_uses_shared_weight': True,
  'lm_head_uses_shared_weight': False,
  'tie_word_embeddings_config': True,
  'expected_alias_missing_keys': [],
  'unexpected_missing_keys': [],
  'unexpected_keys': [],
  'mismatched_keys': [],
  'error_messages': []},
 'train_metrics': {'train_runtime': 318.8679,
  'train_samples_per_second': 5.52,
  'train_steps_per_second': 0.345,
  'total_flos': 288425169321984.0,
  'train_loss': 8.44391361583363,
  'epoch': 5.0},
 'validation_metrics': {'validation_loss': 3.7605254650115967,
  'eval_loss': 3.7605254650115967},
 'test_metrics': {'test_loss': 3.808744192123413},
 'validation_perplexity': 42.971,
 'best_checkpoint': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiments\\flan_t5_base_lora_exp2_v3_20260730_135452\\training\\checkpoint-110',
 'best_metric': 3.7605254650115967,
 'global_step': 110,
 'trainable_parameters': 3538944,
 'total_parameters': 251116800,
 'trainable_percentage': 1.409282,
 'experiment_2_training_fixes': ['warmup_steps replaces deprecated warmup_ratio',
  'the original FLAN-T5 tie_word_embeddings configuration is preserved',
  'shared encoder/decoder embedding aliases are verified after loading',
  'unexpected missing checkpoint parameters stop training',
  'early stopping is removed before final validation/test evaluation']}

Experiment 2 adapter: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\training\lora_adapter

## 8. Inspect the Experiment 2 training artifacts

In [17]:
required_training_artifacts = [
    TRAINING_DIR / "model_metadata.json",
    TRAINING_DIR / "training_curve.png",
    TRAINING_DIR / "training_log_history.json",
    TRAINING_DIR / "training_log_history.csv",
    TRAINING_DIR / "lora_adapter" / "adapter_config.json",
    TRAINING_DIR / "lora_adapter" / "adapter_model.safetensors",
]
artifact_status = pd.DataFrame({
    "artifact": [str(path.relative_to(EXPERIMENT2_DIR)) for path in required_training_artifacts],
    "exists": [path.exists() for path in required_training_artifacts],
    "bytes": [path.stat().st_size if path.exists() else 0 for path in required_training_artifacts],
})
display(artifact_status)
assert artifact_status["exists"].all()

                                          artifact  exists     bytes
0                     training\model_metadata.json    True      4728
1                      training\training_curve.png    True     47447
2               training\training_log_history.json    True      3614
3                training\training_log_history.csv    True      1832
4        training\lora_adapter\adapter_config.json    True      1112
5  training\lora_adapter\adapter_model.safetensors    True  14176016

## 9. Evaluate Base FLAN-T5 versus Experiment 2

This uses the same held-out `benchmark_prompts_v2.jsonl` and the same evaluation
pipeline used for Experiment 1.

In [18]:
from src.advanced_evaluation import run_base_vs_lora_evaluation
from src.config import EvaluationConfig

EXPERIMENT2_EVALUATION_DIR = EXPERIMENT2_DIR / "evaluation"

if RUN_EVALUATION:
    experiment2_evaluation_manifest = run_base_vs_lora_evaluation(
        benchmark_path=PROJECT_ROOT / "data" / "benchmark_prompts_v2.jsonl",
        base_model_id="google/flan-t5-base",
        adapter_path=EXPERIMENT2_ADAPTER_PATH,
        output_dir=EXPERIMENT2_EVALUATION_DIR,
        evaluation_config=EvaluationConfig(
            benchmark_path=str(PROJECT_ROOT / "data" / "benchmark_prompts_v2.jsonl"),
            bootstrap_samples=2000,
            seed=52,
        ),
    )
else:
    experiment2_evaluation_manifest = json.loads(
        (EXPERIMENT2_EVALUATION_DIR / "evaluation_manifest.json").read_text(encoding="utf-8")
    )

display(experiment2_evaluation_manifest["comparison"])

Loading weights: 100%|██████████| 282/282 [00:00<00:00, 28209.44it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4920.76it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 48.04it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 77.06it/s]
Loading weights: 100%|██████████| 389/389 [00:00<00:00, 12138.86it/s]
[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     | Details
--------------------------+------------+--------
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Loading weights: 100%|██████████| 282/282 [00:00<00:00, 17820.94it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8092.41it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 62.79it/s]
Batches: 100%|██████████| 3/3 [00:00<00:00, 62.40it/s]
Loading weights: 100%|██████████| 389/389 [00:00<00:00, 8186.53it/s]
[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     | Details
--------------------------+------------+--------
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

{'status': 'completed',
 'benchmark_examples': 80,
 'metric_comparison': {'instruction_adherence': {'base_mean': 0.623099,
   'lora_mean': 0.685447,
   'mean_delta': 0.062349,
   'delta_95_percent_ci': {'mean': 0.062349,
    'lower': 0.042487,
    'upper': 0.082336,
    'n': 80},
   'lora_win_rate': 0.725,
   'tie_rate': 0.0375},
  'quality_rubric_score': {'base_mean': 0.57925,
   'lora_mean': 0.72825,
   'mean_delta': 0.149,
   'delta_95_percent_ci': {'mean': 0.149,
    'lower': 0.116125,
    'upper': 0.183625,
    'n': 80},
   'lora_win_rate': 0.65,
   'tie_rate': 0.2875},
  'rouge_l_f1': {'base_mean': 0.09508,
   'lora_mean': 0.141876,
   'mean_delta': 0.046796,
   'delta_95_percent_ci': {'mean': 0.046796,
    'lower': 0.034206,
    'upper': 0.05976,
    'n': 80},
   'lora_win_rate': 0.7875,
   'tie_rate': 0.0125},
  'semantic_similarity': {'base_mean': 0.346721,
   'lora_mean': 0.48401,
   'mean_delta': 0.137289,
   'delta_95_percent_ci': {'mean': 0.137289,
    'lower': 0.093198,
    'upper': 0.181817,
    'n': 80},
   'lora_win_rate': 0.7375,
   'tie_rate': 0.0},
  'bertscore_f1': {'base_mean': 0.850759,
   'lora_mean': 0.852739,
   'mean_delta': 0.001981,
   'delta_95_percent_ci': {'mean': 0.001981,
    'lower': -0.001181,
    'upper': 0.005105,
    'n': 80},
   'lora_win_rate': 0.4625,
   'tie_rate': 0.0}},
 'base_hallucination_flag_rate': 0.8125,
 'lora_hallucination_flag_rate': 0.675,
 'hallucination_flag_rate_delta': -0.1375,
 'interpretation': 'A positive metric delta favors LoRA. Confidence intervals quantify sampling uncertainty on this benchmark, not universal model quality.',
 'human_review_required': True}

## 10. Compare Experiment 1 directly with Experiment 2

In [19]:
from src.experiment2_comparison import compare_experiment_runs

EXPERIMENT12_COMPARISON_DIR = (
    EXPERIMENT2_EVALUATION_DIR / "experiment1_vs_experiment2"
)

experiment12_summary = compare_experiment_runs(
    experiment1_evaluation_dir=EXPERIMENT1_DIR / "evaluation",
    experiment2_evaluation_dir=EXPERIMENT2_EVALUATION_DIR,
    output_dir=EXPERIMENT12_COMPARISON_DIR,
)
display(experiment12_summary)

experiment12_review_path = (
    EXPERIMENT12_COMPARISON_DIR
    / "experiment1_vs_experiment2_per_example.csv"
)
print("Experiment 1 vs 2 review file:", experiment12_review_path)

{'status': 'completed',
 'benchmark_examples': 80,
 'metric_comparison': {'instruction_adherence': {'experiment1_mean': 0.680236,
   'experiment2_mean': 0.685447,
   'mean_delta': 0.005211,
   'experiment2_win_rate': 0.5,
   'tie_rate': 0.0125},
  'quality_rubric_score': {'experiment1_mean': 0.85425,
   'experiment2_mean': 0.72825,
   'mean_delta': -0.126,
   'experiment2_win_rate': 0.1125,
   'tie_rate': 0.2},
  'rouge_l_f1': {'experiment1_mean': 0.146136,
   'experiment2_mean': 0.141876,
   'mean_delta': -0.00426,
   'experiment2_win_rate': 0.5375,
   'tie_rate': 0.025},
  'semantic_similarity': {'experiment1_mean': 0.530597,
   'experiment2_mean': 0.48401,
   'mean_delta': -0.046587,
   'experiment2_win_rate': 0.3,
   'tie_rate': 0.0125},
  'bertscore_f1': {'experiment1_mean': 0.85392,
   'experiment2_mean': 0.852739,
   'mean_delta': -0.001181,
   'experiment2_win_rate': 0.425,
   'tie_rate': 0.0125}},
 'experiment1_hallucination_flag_rate': 0.5125,
 'experiment2_hallucination_flag_rate': 0.675,
 'hallucination_flag_rate_delta_exp2_minus_exp1': 0.1625,
 'by_category': {'Concept explanation': {'instruction_adherence': {'experiment1': 0.706942,
    'experiment2': 0.665619,
    'delta': -0.041323},
   'quality_rubric_score': {'experiment1': 0.921613,
    'experiment2': 0.796774,
    'delta': -0.124839},
   'rouge_l_f1': {'experiment1': 0.156071,
    'experiment2': 0.167676,
    'delta': 0.011605},
   'semantic_similarity': {'experiment1': 0.656442,
    'experiment2': 0.618711,
    'delta': -0.037731},
   'bertscore_f1': {'experiment1': 0.857365,
    'experiment2': 0.857446,
    'delta': 8.1e-05}},
  'Metric explanation': {'instruction_adherence': {'experiment1': 0.691367,
    'experiment2': 0.680511,
    'delta': -0.010856},
   'quality_rubric_score': {'experiment1': 0.968889,
    'experiment2': 0.864444,
    'delta': -0.104444},
   'rouge_l_f1': {'experiment1': 0.163752,
    'experiment2': 0.164649,
    'delta': 0.000897},
   'semantic_similarity': {'experiment1': 0.685344,
    'experiment2': 0.575183,
    'delta': -0.110161},
   'bertscore_f1': {'experiment1': 0.856097,
    'experiment2': 0.85212,
    'delta': -0.003977}},
  'Quality analytics': {'instruction_adherence': {'experiment1': 0.657035,
    'experiment2': 0.701925,
    'delta': 0.04489},
   'quality_rubric_score': {'experiment1': 0.77625,
    'experiment2': 0.6445,
    'delta': -0.13175},
   'rouge_l_f1': {'experiment1': 0.134473,
    'experiment2': 0.116757,
    'delta': -0.017716},
   'semantic_similarity': {'experiment1': 0.398249,
    'experiment2': 0.359102,
    'delta': -0.039147},
   'bertscore_f1': {'experiment1': 0.850761,
    'experiment2': 0.849231,
    'delta': -0.00153}}},
 'human_review_required': True,
 'human_review_file': 'C:\\Users\\atripathi\\OneDrive - Veralto\\Desktop\\AI Codes\\GIT Projects\\transformer-projects\\05-instruction-tuned-domain-llm\\outputs\\experiments\\flan_t5_base_lora_exp2_v3_20260730_135452\\evaluation\\experiment1_vs_experiment2\\experiment1_vs_experiment2_per_example.csv',
 'interpretation': 'Positive metric deltas favor Experiment 2. Promotion still requires human factual review.'}

Experiment 1 vs 2 review file: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\evaluation\experiment1_vs_experiment2\experiment1_vs_experiment2_per_example.csv

## 11. Complete Experiment 2 human evaluation

Review:

1. `evaluation/lora_model/manual_review_results.csv`
2. `evaluation/comparison/per_example_base_vs_lora.csv`
3. `evaluation/experiment1_vs_experiment2/experiment1_vs_experiment2_per_example.csv`

For the third file, use only `experiment1`, `experiment2`, or `tie` in
`human_preferred_model`.

In [20]:
exp2_manual_review_path = (
    EXPERIMENT2_EVALUATION_DIR / "lora_model" / "manual_review_results.csv"
)
exp2_base_comparison_path = (
    EXPERIMENT2_EVALUATION_DIR / "comparison" / "per_example_base_vs_lora.csv"
)

print("Experiment 2 model review:", exp2_manual_review_path)
print("Base vs Experiment 2:", exp2_base_comparison_path)
print("Experiment 1 vs Experiment 2:", experiment12_review_path)

comparison_preview = pd.read_csv(experiment12_review_path)
weak_or_flagged = comparison_preview[
    (comparison_preview["delta_exp2_minus_exp1_bertscore_f1"] < 0)
    | (
        comparison_preview["experiment2_hallucination_flag"]
        .astype(str)
        .str.lower()
        .eq("true")
    )
]
display(
    weak_or_flagged[
        [
            "id", "prompt", "experiment1_answer", "experiment2_answer",
            "delta_exp2_minus_exp1_bertscore_f1",
            "experiment2_hallucination_flag",
        ]
    ]
)

Experiment 2 model review: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\evaluation\lora_model\manual_review_results.csv
Base vs Experiment 2: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\evaluation\comparison\per_example_base_vs_lora.csv
Experiment 1 vs Experiment 2: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\evaluation\experiment1_vs_experiment2\experiment1_vs_experiment2_per_example.csv

,id,prompt,experiment1_answer,experiment2_answer,delta_exp2_minus_exp1_bertscore_f1,experiment2_hallucination_flag
0,benchmark_v2_000,Explain supervised learning accurately and inc...,A supervised learning model is a model that le...,A supervised learning model is a model that le...,-0.003051,False
1,benchmark_v2_001,Give a non-confidential quality analytics exam...,Using a manufacturing or process-quality setti...,Modeling supervised learning is a non-confiden...,-0.001734,True
2,benchmark_v2_002,Explain unsupervised learning accurately and i...,Unsupervised learning is a method of learning ...,Unsupervised learning is a method of supervise...,-0.011242,False
3,benchmark_v2_003,Give a non-confidential quality analytics exam...,Unsupervised quality analytics is a method of ...,Unsupervised quality analytics is a non-confid...,0.009449,True
5,benchmark_v2_005,Give a non-confidential quality analytics exam...,Classification is a way of determining the qua...,Modeling is a non-confidential quality analyti...,-0.006894,True
...,...,...,...,...,...,...
73,benchmark_v2_073,Give a non-confidential quality analytics exam...,BERTScore is based on a process-quality settin...,BERTScore is a non-confidential quality analyt...,-0.009253,True
74,benchmark_v2_074,Explain hallucination accurately and include o...,Hallucination is a form of hallucinations. It ...,A hallucination occurs when a person is in a s...,0.016567,True
75,benchmark_v2_075,Give a non-confidential quality analytics exam...,Manufacturing or process-quality is a type of ...,Modeling a manufacturing process is a non-conf...,0.003141,True
77,benchmark_v2_077,Give a non-confidential quality analytics exam...,Model drift occurs when a model drifts in a ma...,Model drift is a non-confidential quality anal...,-0.012344,True
79,benchmark_v2_079,Give a non-confidential quality analytics exam...,A manufacturing or process-quality setting is ...,Quality analytics can be used to measure repro...,0.003942,True

In [21]:
EXPERIMENT2_HUMAN_REVIEW_COMPLETED = True
PROMOTE_EXPERIMENT2 = False

if PROMOTE_EXPERIMENT2 and not EXPERIMENT2_HUMAN_REVIEW_COMPLETED:
    raise RuntimeError(
        "Promotion is blocked until Experiment 2 human review is complete."
    )

print("Experiment 2 human review is complete.")
print("Experiment 2 promotion:", PROMOTE_EXPERIMENT2)

Experiment 2 human review is complete.
Experiment 2 promotion: False

## 12. Apply the Experiment 2 release-quality gate

In [22]:
from src.experiment2_comparison import assess_experiment2_release

release_assessment = assess_experiment2_release(
    experiment2_evaluation_dir=EXPERIMENT2_EVALUATION_DIR,
    experiment_comparison_dir=EXPERIMENT12_COMPARISON_DIR,
)
display(release_assessment)

assessment_path = EXPERIMENT2_DIR / "experiment2_release_assessment.json"
assessment_path.write_text(
    json.dumps(release_assessment, indent=2),
    encoding="utf-8",
)
print("Saved:", assessment_path)

{'ready': False,
 'checks': {'all_exp2_ratings_completed': True,
  'all_exp1_vs_exp2_preferences_completed': True,
  'experiment2_preference_rate_at_least_60_percent': False,
  'mean_factuality_at_least_4': False,
  'mean_relevance_at_least_4': False,
  'mean_clarity_at_least_4': False,
  'mean_instruction_following_at_least_4': False,
  'human_hallucination_rate_below_10_percent': False},
 'experiment2_rating_means': {'human_factuality_1_to_5': 1.4875,
  'human_relevance_1_to_5': 1.875,
  'human_clarity_1_to_5': 2.1375,
  'human_instruction_following_1_to_5': 1.0375},
 'experiment1_vs_experiment2_preferences': {'experiment1': 57,
  'experiment2': 12,
  'tie': 11,
  'missing': 0},
 'experiment2_preference_rate': 0.15,
 'experiment2_human_hallucination_rate': 0.5375,
 'decision': 'do_not_promote_yet'}

Saved: C:\Users\atripathi\OneDrive - Veralto\Desktop\AI Codes\GIT Projects\transformer-projects\05-instruction-tuned-domain-llm\outputs\experiments\flan_t5_base_lora_exp2_v3_20260730_135452\experiment2_release_assessment.json

## 13. Promote only after the gate passes

In [23]:
from src.release_utils import promote_experiment

if PROMOTE_EXPERIMENT2:
    if not EXPERIMENT2_HUMAN_REVIEW_COMPLETED:
        raise RuntimeError("Human review is incomplete.")
    if not release_assessment.get("ready", False):
        raise RuntimeError(
            "Experiment 2 did not meet the release-quality thresholds. "
            "Keep it as an experiment and improve the dataset or training."
        )
    release_manifest = promote_experiment(
        project_root=PROJECT_ROOT,
        experiment_dir=EXPERIMENT2_DIR,
        human_review_completed=True,
    )
    display(release_manifest)
else:
    print(
        "Promotion skipped. Experiment 1 remains preserved, and Experiment 2 "
        "remains an evaluated candidate until human review and thresholds pass."
    )

Promotion skipped. Experiment 1 remains preserved, and Experiment 2 remains an evaluated candidate until human review and thresholds pass.

## Final evidence to keep

Commit the code, curated data assets, notebook, dataset quality report, training
curve, metric summaries, comparison charts, and reviewed CSV files. Keep full
adapter ZIP archives outside ordinary Git history or publish the approved
adapter to a Hugging Face model repository.